(executable
 (name main)
 (modules main sys_io)
 (libraries kanon_kernel kanon_surface))

(executable
 (name sl_surface)
 (modules sl_surface)
 (libraries kanon_kernel kanon_surface))

(rule
 (alias runtest)
 (deps (source_tree fixtures) (source_tree neg) (source_tree erase-neg)
       (source_tree golden))
 (action (run %{exe:main.exe} .)))

(rule
 (alias runtest)
 (action (run %{exe:sl_surface.exe})))
