(copy_files ../../test/sys_io.ml)

(executable
 (name prop_index)
 (modules prop_index)
 (libraries kanon_kernel kanon_surface))

(rule
 (alias runtest)
 (action (run %{exe:prop_index.exe})))

(executables
 (names opaque_test inline_test)
 (modules opaque_test inline_test sys_io)
 (libraries kanon_kernel kanon_surface attest_erase))

(rule
 (alias runtest)
 (deps (source_tree ../../fixtures/erasure))
 (action (chdir %{workspace_root} (run %{exe:opaque_test.exe}))))

(rule
 (alias runtest)
 (deps (source_tree ../../fixtures/erasure))
 (action (chdir %{workspace_root} (run %{exe:inline_test.exe}))))
